using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace UserIdIssuer;

public class Utils
{
    public static readonly string parentDirectoryPath = Path.Combine(Directory.GetCurrentDirectory(), "BepInEx");
    public static readonly string filePath = Path.Combine(parentDirectoryPath, "user_id.txt");
    internal static void IssueUserId()
    {
        UserIdLogger.Debug("Issuing user ID...");

        try
        {
            var fileText = new StringBuilder();
            fileText.AppendLine($"Generated by UserIdIssuer-{UserIdIssuerPlugin.VersionString + (UserIdIssuerPlugin.IsDevRelease ? "-indev" : "")} ({UserIdIssuerPlugin.Id})");
            fileText.Append("\n");
            fileText.AppendLine("This file contains the user ID issued by UserIdIssuer");
            fileText.AppendLine("This ID is used as an identifier by certain mods, and is unique");
            fileText.AppendLine("DO NOT share, edit, or delete this file, as it may cause issues with mods that rely on the user ID");
            fileText.AppendLine("For example, in the mod Goober's TOU:M Ranked, if you change your ID all your stats reset.");

            var userId = Guid.NewGuid().ToString();

            fileText.Append("\n\n<id>");
            fileText.Append(userId);
            fileText.Append("</id>");

            File.WriteAllText(filePath, fileText.ToString());
            UserIdLogger.Info("User ID issued");
            UserIdLogger.Warn("KEEP YOUR USER ID PRIVATE!");
            UserIdLogger.Debug($"User ID: {userId}");
        }
        catch (Exception exception)
        {
            UserIdLogger.Error("An error occurred while issuing user ID");
            UserIdLogger.Error(exception.Message);
        }
    }
    internal static bool checkForId()
    {
        if (File.Exists(filePath))
        {
            return true;
        } else
        {
            return false;
        }
    }

    public static string getUserId()
    {
        if (checkForId())
        {
            string content = File.ReadAllText(filePath);

            Match match = Regex.Match(content, @"<id>(.*?)</id>", RegexOptions.Singleline);

            if (match.Success)
            {
                string idValue = match.Groups[1].Value;
                return idValue;
            }
            else
            {
                UserIdLogger.Error("No <id> tag found.");
                return "";
            }
        } else
        {
            UserIdLogger.Error("UserID hasn't been generated yet");
            return "";
        }
    }
}